### ISSUE TITLE
UpgradeConfig CR with LOCAL config does not sync. #881

### ISSUE THREAD

**Issue by usamaahmadkhan** [openshift/managed-upgrade-operator#258]
Operator Image: quay.io/app-sre/managed-upgrade-operator:latest

Operator keeps reconciling but doesn't add status fields to the UpgradeConfig CR:

```
{"level":"info","ts":1626093892.7293298,"msg":"Using local CR as the upgrade config provider"}
{"level":"info","ts":1626093892.731769,"logger":"upgradeconfig-localprovider","msg":"Read the upgrade config from the cluster directly"}
{"level":"info","ts":1626094079.5829825,"logger":"controller_machineconfigpool","msg":"Reconciling MachineConfigPool","Request.Namespace":"","Request.Name":"worker"}
{"level":"info","ts":1626094174.783578,"msg":"Using local CR as the upgrade config provider"}
{"level":"info","ts":1626094174.78903,"logger":"upgradeconfig-localprovider","msg":"Read the upgrade config from the cluster directly"}
{"level":"info","ts":1626094375.0481997,"logger":"controller_machineconfigpool","msg":"Reconciling MachineConfigPool","Request.Namespace":"","Request.Name":"worker"}
```

UpgradeConfig CR:
```
apiVersion: upgrade.managed.openshift.io/v1alpha1
kind: UpgradeConfig
metadata:
  name: managed-upgrade-config
  namespace: openshift-managed-upgrade-operator
spec:
  type: "OSD"
  upgradeAt: "2021-07-06T10:00:00Z"
  PDBForceDrainTimeout: 60
  capacityReservation: true
  desired:
    channel: "stable-4.7"
    version: "4.7.18"
```

Config:
```
apiVersion: v1
kind: ConfigMap
metadata:
  name: managed-upgrade-operator-config
  namespace: openshift-managed-upgrade-operator
data:
  config.yaml: |
    configManager:
      source: LOCAL
      localConfigName: managed-upgrade-config
      watchInterval: 5
    maintenance:
      controlPlaneTime: 90
      ignoredAlerts:
        controlPlaneCriticals:
        - ClusterOperatorDown
        - ClusterOperatorDegraded
    scale:
      timeOut: 30
    upgradeWindow:
      delayTrigger: 30
      timeOut: 120
    nodeDrain:
      timeOut: 45
      expectedNodeDrainTime: 8
    healthCheck:
      ignoredCriticals:
      - DNSErrors05MinSRE
      - MetricsClientSendFailingSRE
      - UpgradeNodeScalingFailedSRE
      - UpgradeClusterCheckFailedSRE
      - PrometheusRuleFailures
      - CannotRetrieveUpdates
      - FluentdNodeDown
      ignoredNamespaces:
      - openshift-logging
      - openshift-redhat-marketplace
      - openshift-operators
      - openshift-customer-monitoring
      - openshift-route-monitoring-operator
      - openshift-user-workload-monitoring
      - openshift-pipelines
    extDependencyAvailabilityChecks: {}
    verification:
      ignoredNamespaces:
      - openshift-logging
      namespacePrefixesToCheck:
      - openshift
      - kube
      - default
```
