### ISSUE TITLE
Operator unable to find an available upgrade 

### ISSUE THREAD

**Issue by bodz1lla** [openshift/managed-upgrade-operator#393]
The managed-upgrade-operator is encountering an issue where it is unable to find an available upgrade e.g. clusterversion `4.13.19`. 

UpgradeConfig
```
apiVersion: upgrade.managed.openshift.io/v1alpha1
kind: UpgradeConfig
metadata:
  name: managed-upgrade-config
  namespace: openshift-managed-upgrade-operator
spec:
  PDBForceDrainTimeout: 60
  capacityReservation: false
  desired:
    channel: stable-4.13
    version: 4.13.19
  type: OSD
  upgradeAt: "2023-11-14T08:00:00Z"
```

The operator reports the following error:
```
ts=2023-11-14T08:46:01Z level=info logger=controller_upgradeconfig msg="An error occurred while validating UpgradeConfig: no available upgrade for the given clusterversion 4.13.19" Request.Namespace=openshift-managed-upgrade-operator Request.Name=managed-upgrade-config
ts=2023-11-14T08:46:01Z level=error logger=controller.upgradeconfig-controller msg="Reconciler error" name=managed-upgrade-config namespace=openshift-managed-upgrade-operator error="no available upgrade for the given clusterversion 4.13.19" stacktrace="sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Start.func2.2\n\tpkg/mod/sigs.k8s.io/controller-runtime@v0.10.0/pkg/internal/controller/controller.go:227"
ts=2023-11-14T08:48:33Z level=info logger=controller_machineconfigpool msg="Reconciling MachineConfigPool" Request.Namespace= Request.Name=worker
ts=2023-11-14T08:50:45Z level=info logger=controller_upgradeconfig msg="Reconciling UpgradeConfig" Request.Namespace=openshift-managed-upgrade-operator Request.Name=managed-upgrade-config
ts=2023-11-14T08:50:45Z level=info logger=controller_upgradeconfig msg="Current cluster status" Request.Namespace=openshift-managed-upgrade-operator Request.Name=managed-upgrade-config status=New
ts=2023-11-14T08:50:45Z level=info logger=controller_upgradeconfig msg="Validating UpgradeConfig" Request.Namespace=openshift-managed-upgrade-operator Request.Name=managed-upgrade-config
```

**Environment**: 
OpenShift Cluster Version: 4.13.14

**Manual Upgrade via Console UI**
If you upgrade the cluster manually through the console UI, you have the option to select the desired version and execute the update manually. This is an alternative workaround.

Any information would be helpful.
